CREATE TABLE IF NOT EXISTS space_pets (
    id INT AUTO_INCREMENT PRIMARY KEY,
    spaceId INT NOT NULL,
    name VARCHAR(128) NOT NULL,
    type VARCHAR(32) NOT NULL DEFAULT 'pet',
    mood TINYINT NOT NULL DEFAULT 50,
    health TINYINT NOT NULL DEFAULT 80,
    energy TINYINT NOT NULL DEFAULT 60,
    hydration TINYINT NOT NULL DEFAULT 60,
    intimacy TINYINT NOT NULL DEFAULT 50,
    updatedAt BIGINT NOT NULL,
    FOREIGN KEY (spaceId) REFERENCES spaces(id) ON DELETE CASCADE
);
